package lib

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Coverage renders the AC → slice(s) → proven traceability matrix for a feature,
// deterministically, from its workspace artifacts (spec.md / tasks.md / seal.md).
// It is the living map /rite-prove and /rite-seal walk to prove every acceptance
// criterion is covered by a slice and proven in the seal. Read-only.
//
// The convention pairs with check-acceptance: a criterion carries a stable id,
// spec.md declares `- [ ] [ACn] …`, a tasks.md slice claims it with a
// `Satisfies: ACn` line, and seal.md proves it with `- [x] [ACn] …`. A criterion
// is proven iff its `[ACn]` id is checked in seal.md.
//
// base is the project directory that contains the .devrites tree; slug defaults
// to the active feature named in .devrites/ACTIVE. The matrix is the stdout
// contract; stderr carries only the no-workspace / no-spec diagnostics.
//
//	0  matrix rendered
//	2  no active workspace, no workspace directory, or no spec.md to map
func Coverage(root string, args []string, stdout, stderr io.Writer) int {
	slug := ""
	if len(args) > 0 {
		slug = args[0]
	}
	if slug == "" {
		slug = activeSlug(root)
	}
	if slug == "" {
		fmt.Fprintln(stderr, "coverage: no active workspace.")
		return 2
	}

	dir := featureDir(root, slug)
	if !isDir(dir) {
		fmt.Fprintf(stderr, "coverage: no workspace at %s.\n", dir)
		return 2
	}

	specBytes, err := os.ReadFile(filepath.Join(dir, "spec.md"))
	if err != nil {
		fmt.Fprintln(stderr, "coverage: no spec.md — nothing to map.")
		return 2
	}

	// tasks.md / seal.md are optional inputs — a missing one just yields
	// UNCOVERED slices / pending proof, never an error.
	tasks, haveTasks := readFileOK(filepath.Join(dir, "tasks.md"))
	seal, haveSeal := readFileOK(filepath.Join(dir, "seal.md"))

	fmt.Fprintf(stdout, "# Coverage matrix: %s\n", slug)
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "| AC | Slice(s) | Proven in seal? |")
	fmt.Fprintln(stdout, "|----|----------|-----------------|")

	for _, ac := range acIDs(string(specBytes)) {
		slices := ""
		if haveTasks {
			slices = slicesForAC(tasks, ac)
		}
		if slices == "" {
			slices = "— (UNCOVERED)"
		}
		proven := "pending"
		if haveSeal && provenInSeal(seal, ac) {
			proven = "yes"
		}
		fmt.Fprintf(stdout, "| %s | %s | %s |\n", ac, slices, proven)
	}

	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "_Generated by devrites-engine coverage from spec.md / tasks.md / seal.md. UNCOVERED rows block /rite-vet's analyze gate._")
	return 0
}

// acIDRe (`\[AC[0-9]+\]`) is shared with check-acceptance, which declares it.
var (
	sliceHeaderRe = regexp.MustCompile(`^##[[:space:]]*Slice`)
	sliceStripRe  = regexp.MustCompile(`^##[[:space:]]*`)
	satisfiesRe   = regexp.MustCompile(`^[[:space:]]*Satisfies:`)
)

// acIDs returns the unique `[ACn]` ids declared in spec.md, bracket-stripped and
// byte-order sorted — mirroring `grep -oE '\[AC[0-9]+\]' | tr -d '[]' | sort -u`
// under LC_ALL=C.
func acIDs(spec string) []string {
	seen := map[string]bool{}
	var ids []string
	for _, m := range acIDRe.FindAllString(spec, -1) {
		id := strings.Trim(m, "[]")
		if !seen[id] {
			seen[id] = true
			ids = append(ids, id)
		}
	}
	sort.Strings(ids)
	return ids
}

// slicesForAC returns the `;`-joined slice headers whose `Satisfies:` line names
// ac, in file order. It reproduces the script's awk exactly, including its two
// quirks: the current `## Slice …` header persists to the next Satisfies line,
// and the match is a substring test — so ac "AC1" also matches a slice that
// satisfies "AC10". Faithful parity requires preserving both.
func slicesForAC(tasks, ac string) string {
	var matched []string
	cur := ""
	sc := newLineScanner(strings.NewReader(tasks))
	for sc.Scan() {
		line := sc.Text()
		if sliceHeaderRe.MatchString(line) {
			cur = sliceStripRe.ReplaceAllString(line, "")
		}
		if satisfiesRe.MatchString(line) && strings.Contains(line, ac) {
			matched = append(matched, cur)
		}
	}
	return strings.Join(matched, ";")
}

// provenInSeal reports whether seal.md checks off ac's id — a line of the form
// `- [x] [ACn]` (with optional surrounding whitespace), the same pattern the
// script greps for.
func provenInSeal(seal, ac string) bool {
	re := regexp.MustCompile(`(?m)^[[:space:]]*-[[:space:]]*\[x\][[:space:]]*\[` + regexp.QuoteMeta(ac) + `\]`)
	return re.MatchString(seal)
}

// readFileOK reads a file, returning its contents and whether it existed and
// read cleanly.
func readFileOK(path string) (string, bool) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	return string(b), true
}
