#!/usr/bin/env bash
# coverage.sh — render the AC -> slice(s) -> test -> evidence-status traceability matrix
# for a feature, from the workspace artifacts. The living map /rite-prove and /rite-seal
# walk to prove every acceptance criterion is covered and proven. Read-only; deterministic.
#
# Convention (pairs with check-acceptance.sh): acceptance criteria carry a stable id —
#   spec.md  "## Acceptance criteria"  ->  - [ ] [AC1] <criterion>
#   tasks.md slice                     ->  Satisfies: AC1, AC2
#   seal.md  "## Acceptance Criteria"  ->  - [x] [AC1] <criterion> — evidence: <...>
# A criterion is proven iff its [ACn] id is checked ([x]) in seal.md.
#
# Usage: coverage.sh [slug]    (slug defaults to .devrites/ACTIVE)
# Exit:  0 rendered · 2 no workspace
set -u

slug="${1:-}"
[ -n "$slug" ] || slug="$(cat .devrites/ACTIVE 2>/dev/null || true)"
[ -n "$slug" ] || { echo "coverage: no active workspace." >&2; exit 2; }
d=".devrites/work/$slug"
[ -d "$d" ] || { echo "coverage: no workspace at $d." >&2; exit 2; }

spec="$d/spec.md"; tasks="$d/tasks.md"; seal="$d/seal.md"

[ -f "$spec" ] || { echo "coverage: no spec.md — nothing to map." >&2; exit 2; }

echo "# Coverage matrix: $slug"
echo
echo "| AC | Slice(s) | Proven in seal? |"
echo "|----|----------|-----------------|"

# Each [ACn] id mentioned in spec.md.
grep -oE '\[AC[0-9]+\]' "$spec" 2>/dev/null | tr -d '[]' | sort -u | while IFS= read -r ac; do
  [ -n "$ac" ] || continue
  # Slices whose "Satisfies:" line names this AC.
  slices=""
  if [ -f "$tasks" ]; then
    slices="$(awk -v ac="$ac" '
      /^##[[:space:]]*Slice/ { s=$0; sub(/^##[[:space:]]*/,"",s) }
      /^[[:space:]]*Satisfies:/ { if (index($0, ac)) { gsub(/^##[[:space:]]*/,"",s); print s } }
    ' "$tasks" | paste -sd ';' - 2>/dev/null)"
  fi
  [ -n "$slices" ] || slices="— (UNCOVERED)"
  proven="pending"
  if [ -f "$seal" ] && grep -qE "^[[:space:]]*-[[:space:]]*\[x\][[:space:]]*\[$ac\]" "$seal" 2>/dev/null; then
    proven="yes"
  fi
  printf '| %s | %s | %s |\n' "$ac" "$slices" "$proven"
done

echo
echo "_Generated by coverage.sh from spec.md / tasks.md / seal.md. UNCOVERED rows block /rite-vet's analyze gate._"
