package harness

import (
	"fmt"
	"strings"
)

// The harness adapter-compliance matrix.
//
// DevRites drives more than one agent runtime from one engine, but the runtimes
// do not expose identical enforcement surfaces. Rather than pretend parity, this
// frozen matrix states, per surface, whether each supported harness enforces it
// natively, through an adapter, or only by instruction the model may ignore. It
// is the single source of truth; `devrites-engine harness-matrix` renders it and
// CI drift-checks the rendered copy in docs/, so the honest picture cannot rot.

// Tier is how strongly a harness backs a given surface, from strongest to
// weakest.
type Tier int

const (
	// Native — the harness exposes the surface directly; the engine hook fires
	// and its decision is honoured.
	Native Tier = iota
	// Adapter — supported, but through a translation shim (a different verb,
	// a mirrored file tree) rather than the harness's first-class path.
	Adapter
	// Instruction — no runtime enforcement surface; the behaviour rides on a
	// directive the model is asked to follow and may under-fire.
	Instruction
	// Conditional — natively supported, but gated on an operator precondition
	// that silently disables it when unmet.
	Conditional
)

func (t Tier) String() string {
	switch t {
	case Native:
		return "Native"
	case Adapter:
		return "Adapter-backed"
	case Instruction:
		return "Instruction-backed"
	case Conditional:
		return "Conditional"
	default:
		return "unknown"
	}
}

// Surface is one enforcement surface and how each harness backs it.
type Surface struct {
	Name   string
	Claude Tier
	Codex  Tier
	Note   string
}

// complianceMatrix is grounded in the shipped wiring: pack/.claude/settings.json
// for Claude, the installer's gen_codex_hooks_json + AGENTS.md merge for Codex.
// Change a cell only when that wiring changes.
var complianceMatrix = []Surface{
	{"SessionStart orientation", Native, Native, "Both wire the orient hook; identical additionalContext envelope."},
	{"PreToolUse allow / deny (allow, a1-guard, reviewer-readonly, wright-scope)", Native, Native, "Codex wires the same PreToolUse guards with agent-type gating."},
	{"PostToolUse sentinel (redwatch)", Native, Native, "Fail-on-red sentinel wired on both."},
	{"Stop gate", Native, Native, "Both honour the {decision:block} convention."},
	{"SubagentStart discipline injection", Native, Native, "subagent-orient wired on both."},
	{"Skill invocation", Native, Adapter, "Claude: native /rite. Codex: $rite over the mirrored .agents/skills tree."},
	{"Reviewer subagent dispatch", Native, Instruction, "Codex under-fires embedded spawns (openai/codex#23496); falls back to .codex/agents + a labelled inline pass."},
	{"Standards step-0 load", Native, Instruction, "Claude: skill Reads core.md. Codex: an AGENTS.md directive to read it."},
	{"Project activation", Native, Conditional, "Codex silently skips every .codex/ layer in an untrusted project until it is trusted."},
}

// Matrix markers delimit the generated block inside a docs file so drift-check
// can extract and compare exactly the rendered region.
const (
	MatrixBeginMarker = "<!-- BEGIN harness-matrix (generated by `devrites-engine harness-matrix`) -->"
	MatrixEndMarker   = "<!-- END harness-matrix -->"
)

// RenderMatrix returns the marker-delimited Markdown block for the matrix. It is
// deterministic — no timestamps — so a committed copy only changes when the
// matrix data does.
func RenderMatrix() string {
	var b strings.Builder
	b.WriteString(MatrixBeginMarker)
	b.WriteString("\n\n| Surface | Claude Code | Codex | Notes |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, s := range complianceMatrix {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", s.Name, s.Claude, s.Codex, s.Note)
	}
	b.WriteString("\nTiers: **Native** (harness enforces it directly) · **Adapter-backed** ")
	b.WriteString("(supported through a translation shim) · **Instruction-backed** ")
	b.WriteString("(no runtime surface — rides on a directive the model may under-fire) · ")
	b.WriteString("**Conditional** (native but gated on an operator precondition).\n\n")
	b.WriteString(MatrixEndMarker)
	return b.String()
}
