package harness

import (
	"fmt"
	"strings"
)

// The compliance matrix records how each harness supports every enforcement
// surface. `devrites-engine harness-matrix` renders this data, and CI compares
// the result with the copy in docs.

// Tier is how strongly a harness backs a given surface, from strongest to
// weakest.
type Tier int

const (
	// Native means the harness exposes and delivers the surface directly. The
	// surface note says whether its policy blocks.
	Native Tier = iota
	// Adapter means a translation layer, such as a different verb or mirrored
	// file tree, provides the surface.
	Adapter
	// Instruction means the runtime has no enforcement surface and relies on a
	// directive that the model may not follow consistently.
	Instruction
	// Conditional means native support depends on an operator precondition.
	Conditional
)

func (t Tier) String() string {
	switch t {
	case Native:
		return "Native"
	case Adapter:
		return "Adapter-backed"
	case Instruction:
		return "Instruction-backed"
	case Conditional:
		return "Conditional"
	default:
		return "unknown"
	}
}

// Surface is one enforcement surface and how each harness backs it.
type Surface struct {
	Name        string
	Claude      Tier
	Codex       Tier
	PhaseImpact string
	Fallback    string
	DoctorCheck string
	Confidence  string
	Note        string
}

// complianceMatrix reflects the shipped wiring in pack/.claude/settings.json
// for Claude and the generated host artifacts plus AGENTS.md for Codex. Change
// a cell only when that wiring changes.
var complianceMatrix = []Surface{
	{"SessionStart orientation", Native, Native, "all phases", "manual preamble/snapshot", "yes", "high", "Both wire the orient hook; identical additionalContext envelope."},
	{"PreToolUse policy (allow, a1-guard, reviewer-readonly, wright-scope)", Conditional, Conditional, "build/review safety", "observe-only findings + human review", "yes", "high", "Both deliver the event, but these policies are non-blocking by default; DEVRITES_HOOK_PROFILE=strict enables every guard, or each guard can be enabled through its documented specific variable."},
	{"Destructive Git authority", Conditional, Conditional, "all shell tool calls", "human permission review; no exact one-shot proof", "yes", "high", "Both wire git-guard at PreToolUse. Standard and strict profiles enforce exact 15-minute one-shot authority; minimal profile or the explicit kill list disables the hook."},
	{"PostToolUse sentinel (redwatch)", Native, Native, "prove/build rest points", "manual red/green check", "yes", "high", "Fail-on-red sentinel wired on both."},
	{"WebFetch ingestion warning trial", Conditional, Instruction, "external research", "inspect retrieved content as untrusted data", "no", "medium", "Claude WebFetch PostToolUse can emit an opt-in metadata-only warning with DEVRITES_INGEST_WARNING=warn; a flagged result remains in context and is omitted from the local source cache. Codex has no matching result event, so this trial is unavailable and silent."},
	{"Stop gate", Conditional, Conditional, "all rest points", "observe-only finding + manual host-specific rite-status", "yes", "high", "Both deliver Stop; stop-gate blocks with DEVRITES_STOP_GATE=enforce or DEVRITES_HOOK_PROFILE=strict."},
	{"SubagentStart discipline injection", Native, Native, "review/build fan-out", "agent file preamble", "yes", "high", "subagent-orient wired on both."},
	{"Skill invocation", Native, Adapter, "all public rites", "explicit file read", "yes", "high", "Claude: native /rite. Codex: $rite over the mirrored .agents/skills tree."},
	{"Reviewer subagent dispatch", Native, Instruction, "review/seal confidence", "labelled inline pass", "partial", "medium", "Codex under-fires embedded spawns (openai/codex#23496); falls back to .codex/agents + a labelled inline pass."},
	{"Standards step-0 load", Native, Instruction, "all phases", "explicit standards read", "partial", "medium", "Claude: skill Reads core.md. Codex: an AGENTS.md directive to read it."},
	{"Project activation", Native, Conditional, "Codex-only startup", "inspect hooks/config, decide trust, then rerun doctor", "yes", "medium", "Codex silently skips every .codex/ layer in an untrusted project; trust remains an operator decision after inspection."},
}

// Matrix markers identify the generated block that the drift check compares.
const (
	MatrixBeginMarker = "<!-- BEGIN harness-matrix (generated by `devrites-engine harness-matrix`) -->"
	MatrixEndMarker   = "<!-- END harness-matrix -->"
)

// RenderMatrix returns the marker-delimited Markdown block. It has no timestamps,
// so its output changes only when the matrix data changes.
func RenderMatrix() string {
	var b strings.Builder
	b.WriteString(MatrixBeginMarker)
	b.WriteString("\n\n| Surface | Claude Code | Codex | Phase impact | Fallback | Doctor check | Confidence | Notes |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for _, s := range complianceMatrix {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s | %s |\n", s.Name, s.Claude, s.Codex, s.PhaseImpact, s.Fallback, s.DoctorCheck, s.Confidence, s.Note)
	}
	b.WriteString("\nTiers: **Native** (the harness exposes and delivers the surface directly; policy notes state whether it blocks) · **Adapter-backed** ")
	b.WriteString("(supported through a translation shim) · **Instruction-backed** ")
	b.WriteString("(no runtime surface: rides on a directive the model may under-fire) · ")
	b.WriteString("**Conditional** (native but gated on an operator precondition).\n\n")
	b.WriteString(MatrixEndMarker)
	return b.String()
}
