#!/usr/bin/env bash
# build-host-artifacts.sh: render host-native Claude, Codex, and omp artifacts
# from the canonical pack.
#
# Default output is pack/generated/ so npm pack can ship prebuilt surfaces.
# Tests may set DEVRITES_HOST_ARTIFACT_DIR to a temporary directory.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd -P)"
PACK_SRC="$ROOT/pack/.claude"
OUT_ROOT="${DEVRITES_HOST_ARTIFACT_DIR:-$ROOT/pack/generated}"

[ -d "$PACK_SRC/skills" ] || { echo "build-host-artifacts: missing $PACK_SRC/skills" >&2; exit 1; }
[ -d "$PACK_SRC/agents" ] || { echo "build-host-artifacts: missing $PACK_SRC/agents" >&2; exit 1; }
[ -d "$PACK_SRC/workflows" ] || { echo "build-host-artifacts: missing $PACK_SRC/workflows" >&2; exit 1; }

TMP_GEN_DIR="$(mktemp -d)"
cleanup() { rm -rf "$TMP_GEN_DIR"; }
trap cleanup EXIT

# shellcheck source=codex-generate.sh
. "$ROOT/scripts/codex-generate.sh"
# shellcheck source=omp-generate.sh
. "$ROOT/scripts/omp-generate.sh"

copy_tree() {
  _src="$1"; _dest="$2"
  mkdir -p "$(dirname "$_dest")"
  rm -rf "$_dest"
  cp -R "$_src" "$_dest"
}

render_codex_skill_tree() {
  _sd="$1"; _dest="$2"
  mkdir -p "$_dest"
  while IFS= read -r f; do
    _r="${f#$_sd/}"
    _out="$_dest/$_r"
    mkdir -p "$(dirname "$_out")"
    case "$_r" in
      SKILL.md)
        _implicit_disabled=0
        if awk 'NR==1&&$0=="---"{fm=1;next} fm&&$0=="---"{exit} fm&&/^disable-model-invocation:[[:space:]]*true/{u=1} END{exit !u}' "$f"; then
          _implicit_disabled=1
        fi
        gen_codex_skill_file "$f" "$_out"
        if [ "$_implicit_disabled" -eq 1 ]; then
          mkdir -p "$_dest/agents"
          printf 'policy:\n  allow_implicit_invocation: false\n' > "$_dest/agents/openai.yaml"
        fi
        ;;
      *.md)
        gen_codex_markdown_file "$f" "$_out"
        ;;
      *)
        cp "$f" "$_out"
        ;;
    esac
  done < <(find "$_sd" -type f)
}

render_omp_skill_tree() {
  _sd="$1"; _dest="$2"
  mkdir -p "$_dest"
  while IFS= read -r f; do
    _r="${f#$_sd/}"
    _out="$_dest/$_r"
    mkdir -p "$(dirname "$_out")"
    case "$_r" in
      SKILL.md)
        gen_omp_skill_file "$f" "$_out"
        ;;
      *.md)
        gen_omp_markdown_file "$f" "$_out"
        ;;
      *)
        cp "$f" "$_out"
        ;;
    esac
  done < <(find "$_sd" -type f)
}

rm -rf "$OUT_ROOT"
mkdir -p "$OUT_ROOT/claude" "$OUT_ROOT/codex" "$OUT_ROOT/omp"

# Claude artifacts are host-native copies of the canonical pack.
copy_tree "$PACK_SRC/skills" "$OUT_ROOT/claude/skills"
copy_tree "$PACK_SRC/agents" "$OUT_ROOT/claude/agents"
copy_tree "$PACK_SRC/workflows" "$OUT_ROOT/claude/workflows"
# Local editor caches under .impeccable/ must never ship in generated hosts.
rm -rf "$OUT_ROOT/claude/agents/.impeccable" "$OUT_ROOT/claude/skills/.impeccable"
cp "$PACK_SRC/settings.json" "$OUT_ROOT/claude/settings.json"

# Codex artifacts are generated host-native mirrors.
mkdir -p "$OUT_ROOT/codex/skills" "$OUT_ROOT/codex/agents"
while IFS= read -r d; do
  name="$(basename "$d")"
  [ "$name" = ".impeccable" ] && continue
  render_codex_skill_tree "$d" "$OUT_ROOT/codex/skills/$name"
done < <(find "$PACK_SRC/skills" -mindepth 1 -maxdepth 1 -type d)

while IFS= read -r f; do
  name="$(basename "$f" .md)"
  gen_codex_agent "$f" "$OUT_ROOT/codex/agents/$name.toml"
done < <(find "$PACK_SRC/agents" -maxdepth 1 -type f -name '*.md')

gen_codex_agents_bridge "$OUT_ROOT/codex/AGENTS.md"
gen_codex_config_toml "$OUT_ROOT/codex/config.toml"

# omp artifacts are generated host-native mirrors (Markdown agents, no TOML).
mkdir -p "$OUT_ROOT/omp/skills" "$OUT_ROOT/omp/agents"
while IFS= read -r d; do
  name="$(basename "$d")"
  [ "$name" = ".impeccable" ] && continue
  render_omp_skill_tree "$d" "$OUT_ROOT/omp/skills/$name"
done < <(find "$PACK_SRC/skills" -mindepth 1 -maxdepth 1 -type d)

while IFS= read -r f; do
  name="$(basename "$f" .md)"
  gen_omp_agent "$f" "$OUT_ROOT/omp/agents/$name.md"
done < <(find "$PACK_SRC/agents" -maxdepth 1 -type f -name '*.md')

gen_omp_plugin_json "$OUT_ROOT/omp/.omp-plugin/plugin.json"

cat > "$OUT_ROOT/README.md" <<'EOF'
# Generated DevRites Host Artifacts

This directory is generated by `scripts/build-host-artifacts.sh`.

- `claude/` contains Claude Code-native skills, agents, read-only workflow adapters, and settings.
- `codex/` contains Codex-native skill mirrors, custom-agent TOML, the
  read-only-root permission profile, and AGENTS bridge content.
- `omp/` contains omp-native skill mirrors, Markdown agents, and
  `.omp-plugin/plugin.json`.

Do not edit these files by hand. Edit `pack/.claude/`,
`scripts/codex-generate.sh`, or `scripts/omp-generate.sh`, then rebuild.
EOF

echo "build-host-artifacts: wrote $OUT_ROOT"
