#!/usr/bin/env bash
# build-host-artifacts.sh — render host-native Claude and Codex artifacts from
# the canonical pack.
#
# Default output is pack/generated/ so npm pack can ship prebuilt surfaces.
# Tests may set DEVRITES_HOST_ARTIFACT_DIR to a temporary directory.
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd -P)"
PACK_SRC="$ROOT/pack/.claude"
OUT_ROOT="${DEVRITES_HOST_ARTIFACT_DIR:-$ROOT/pack/generated}"

[ -d "$PACK_SRC/skills" ] || { echo "build-host-artifacts: missing $PACK_SRC/skills" >&2; exit 1; }
[ -d "$PACK_SRC/agents" ] || { echo "build-host-artifacts: missing $PACK_SRC/agents" >&2; exit 1; }

TMP_GEN_DIR="$(mktemp -d 2>/dev/null || echo "${TMPDIR:-/tmp}/devrites-host-artifacts.$$")"
cleanup() { rm -rf "$TMP_GEN_DIR"; }
trap cleanup EXIT

# shellcheck source=codex-generate.sh
. "$ROOT/scripts/codex-generate.sh"

copy_tree() {
  _src="$1"; _dest="$2"
  mkdir -p "$(dirname "$_dest")"
  rm -rf "$_dest"
  cp -R "$_src" "$_dest"
}

render_codex_skill_tree() {
  _sd="$1"; _dest="$2"
  mkdir -p "$_dest"
  while IFS= read -r f; do
    _r="${f#$_sd/}"
    _out="$_dest/$_r"
    mkdir -p "$(dirname "$_out")"
    case "$_r" in
      SKILL.md)
        _internal=0
        _implicit_disabled=0
        if awk 'NR==1&&$0=="---"{fm=1;next} fm&&$0=="---"{exit} fm&&/^user-invocable:[[:space:]]*false/{u=1} END{exit !u}' "$f"; then
          _internal=1
        fi
        if awk 'NR==1&&$0=="---"{fm=1;next} fm&&$0=="---"{exit} fm&&/^disable-model-invocation:[[:space:]]*true/{u=1} END{exit !u}' "$f"; then
          _implicit_disabled=1
        fi
        gen_codex_skill_file "$f" "$_out" "$_internal"
        if [ "$_internal" -eq 1 ] || [ "$_implicit_disabled" -eq 1 ]; then
          mkdir -p "$_dest/agents"
          printf 'policy:\n  allow_implicit_invocation: false\n' > "$_dest/agents/openai.yaml"
        fi
        ;;
      *.md)
        gen_codex_markdown_file "$f" "$_out"
        ;;
      *)
        cp "$f" "$_out"
        ;;
    esac
  done < <(find "$_sd" -type f)
}

rm -rf "$OUT_ROOT"
mkdir -p "$OUT_ROOT/claude" "$OUT_ROOT/codex"

# Claude artifacts are host-native copies of the canonical pack.
copy_tree "$PACK_SRC/skills" "$OUT_ROOT/claude/skills"
copy_tree "$PACK_SRC/agents" "$OUT_ROOT/claude/agents"
cp "$PACK_SRC/settings.json" "$OUT_ROOT/claude/settings.json"

# Codex artifacts are generated host-native mirrors.
mkdir -p "$OUT_ROOT/codex/skills" "$OUT_ROOT/codex/agents"
while IFS= read -r d; do
  name="$(basename "$d")"
  render_codex_skill_tree "$d" "$OUT_ROOT/codex/skills/$name"
done < <(find "$PACK_SRC/skills" -mindepth 1 -maxdepth 1 -type d)

while IFS= read -r f; do
  name="$(basename "$f" .md)"
  gen_codex_agent "$f" "$OUT_ROOT/codex/agents/$name.toml"
done < <(find "$PACK_SRC/agents" -maxdepth 1 -type f -name '*.md')

gen_codex_agents_bridge "$OUT_ROOT/codex/AGENTS.md"
gen_codex_hooks_json "$OUT_ROOT/codex/hooks.json"

cat > "$OUT_ROOT/README.md" <<'EOF'
# Generated DevRites Host Artifacts

This directory is generated by `scripts/build-host-artifacts.sh`.

- `claude/` contains Claude Code-native skills, agents, and settings.
- `codex/` contains Codex-native skill mirrors, custom-agent TOML, hook
  blocks, and AGENTS bridge content.

Do not edit these files by hand. Edit `pack/.claude/` or
`scripts/codex-generate.sh`, then rebuild.
EOF

echo "build-host-artifacts: wrote $OUT_ROOT"
