#!/usr/bin/env python3
"""Cross-reference linter for the DevRites pack.

Catches the maintenance-drift class the skills audit surfaced: a SKILL.md or
reference file pointing at another file that has moved, been renamed, or never
existed. Four checks, tuned for near-zero false positives:

  1. Markdown links to local .md targets : `](path.md)` resolved relative to the
     containing file; the target must exist.
  2. Bare backtick .md filenames         : `` `name.md` `` must resolve from the
     containing file the way a host opener would (same directory, skill root, or
     ``skill/reference/``). Shared ``devrites-lib`` standards that only exist
     elsewhere must use a relative path or markdown link — basename-anywhere is
     not enough (PI/hosts otherwise open ``<skill>/reference/<name>.md``).
  3. "canonical version: `path`" claims   : the named path (relative to the skills
     root) must exist. Catches a file disclaiming itself secondary to a missing one.
  4. Unquoted ``skill/reference/*.md`` tokens : hosts join those onto the current
     skill (``devrites-lib/reference/afk-discipline.md``). Require
     ``.claude/skills/<skill>/...`` or a relative markdown link. Skip HTML
     comments, backticks, markdown link targets, and paths after ``/``.

Scans pack/.claude/. Exit 1 on any dead reference. Read-only.
"""
import argparse
import os
import re
import sys

parser = argparse.ArgumentParser()
parser.add_argument("--root", default=".", help="repository root containing pack/.claude")
args = parser.parse_args()

REPO_ROOT = os.path.normpath(args.root)
ROOT = os.path.join(REPO_ROOT, "pack", ".claude")
SKILLS_ROOT = os.path.join(ROOT, "skills")

# Runtime artifacts live under .devrites/ (per-feature work/<slug>/ files, plus the
# project-level conventions ledger), not in the pack. References to them by filename are
# legitimate, not dead refs.
WORKSPACE_ARTIFACTS = {
    "spec.md", "plan.md", "tasks.md", "state.md", "decisions.md", "assumptions.md",
    "questions.md", "drift.md", "evidence.md", "browser-evidence.md", "touched-files.md",
    "review.md", "seal.md", "ship.md", "brief.md", "design-brief.md", "strategy.md",
    "polish-report.md", "handoff.md", "eng-review.md", "test-plan.md", "references.md",
    "conventions.md", "coverage.md", "analysis.md", "learnings.md",
    # developer-experience scorecard (work/<slug>/devex.md) + project-level retro ledger (.devrites/retro.md)
    "devex.md", "retro.md",
    # spec-quality checklists (.devrites/work/<slug>/checklists/<domain>.md)
    "functional.md", "data-model.md", "interaction.md", "non-functional.md", "edge-cases.md",
    # Planning artifacts generated by the lifecycle in work/<slug>/.
    "architecture.md", "traceability.md", "flows.md",
    # Named outputs created in the user's workspace by their owning workflow.
    "agent.md", "dogfood.md", "walkthrough.md", "ai-spec.md", "investigation-map.md",
    # Parallel batch lease under .devrites/work/<slug>/ (rite-build --parallel).
    "parallel-lease.md",
    # rite-explain primary output (.devrites/explainers/<date>-<slug>/).
    "explainer.md",
    # visual/ dual-read companion suffix (visual/<name>.outline.md).
    ".outline.md",
    # Clarify scan ledger under work/<slug>/.
    "decision-coverage.md",
}

# Files the skills legitimately tell Claude to read in the USER's project / the repo,
# which are not part of the shipped pack.
PROJECT_DOCS = {
    "CLAUDE.md", "AGENTS.md", "DESIGN.md", "PRODUCT.md", "CONTEXT.md", "NOTES.md",
    "README.md", "CHANGELOG.md", "CONTRIBUTING.md", "NOTICE.md", "cli.md",
    "ADR-NNN.md",  # generated per-decision ADR in the user repo (docs/adr/), promoted at /rite-ship
}

# Paths that are runtime/install roots, not pack-relative skill files.
ALLOW_PATH_PREFIXES = (
    ".devrites/",
    "docs/",
    "visual/",
)


def resolve(here, link):
    """Resolve a link. Host-rooted install paths are mapped to the canonical pack
    tree in this repo; everything else is relative to the containing file.

    Never join ``pack/`` + ``.agents/...`` (that resolves to a missing
    ``pack/.agents`` tree). Codex's ``.agents/skills`` and ``.agents/agents``
    mirrors are generated from ``pack/.claude/``.
    """
    for prefix in (".claude/", ".agents/", ".omp/", ".pi/", ".devin/"):
        if link.startswith(prefix):
            rest = link[len(prefix):]
            return os.path.normpath(os.path.join(REPO_ROOT, "pack", ".claude", rest))
    if link.startswith("docs/"):
        return os.path.normpath(os.path.join(REPO_ROOT, link))
    return os.path.normpath(os.path.join(here, link))


def skill_dir_for(path):
    """Return the owning skill directory for a file under skills/, else None."""
    try:
        rel = os.path.relpath(path, SKILLS_ROOT)
    except ValueError:
        return None
    if rel.startswith(".."):
        return None
    parts = rel.split(os.sep)
    if not parts or parts[0] in (".", ""):
        return None
    return os.path.join(SKILLS_ROOT, parts[0])


def naive_local_candidates(path, base):
    """Locations a host opener typically tries for a bare `` `name.md` ``."""
    here = os.path.dirname(path)
    cands = [os.path.join(here, base)]
    skill = skill_dir_for(path)
    if skill:
        cands.append(os.path.join(skill, base))
        cands.append(os.path.join(skill, "reference", base))
    return cands


if not os.path.isdir(ROOT):
    print(f"check-cross-refs: missing {ROOT} (pass --root <repository>)")
    sys.exit(1)

SKIP_WALK_DIRS = {".git", ".worktrees", "node_modules", ".impeccable"}
md_files = []
all_basenames = set()
for base, dirs, files in os.walk(ROOT):
    dirs[:] = [d for d in dirs if d not in SKIP_WALK_DIRS]
    for f in files:
        if f.endswith(".md"):
            p = os.path.join(base, f)
            md_files.append(p)
            all_basenames.add(f)

LINK_RE = re.compile(r"\]\(([^)]+)\)")
BACKTICK_MD_RE = re.compile(r"`([A-Za-z0-9._/\-]+\.md)(?:#[^`]*)?`")
SEE_RE = re.compile(r"\(see\s+`?([A-Za-z0-9._/\-]+\.md)`?[^)]*\)")
CANONICAL_RE = re.compile(r"[Cc]anonical version:\s*`?\s*`?([A-Za-z0-9._/\-]+\.md)`")
UNQUOTED_SKILL_PATH_RE = re.compile(
    r"(?:rite|devrites)-[a-z0-9-]+/(?:reference|standards)/[A-Za-z0-9_./-]+\.md"
)
HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.S)
HOST_SKILL_PREFIXES = (
    ".claude/skills/",
    ".agents/skills/",
    ".pi/skills/",
    ".omp/skills/",
    ".devin/skills/",
)

errors = []

for path in md_files:
    try:
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
    except OSError as exc:
        errors.append(f"{path}: cannot read markdown file: {exc}")
        continue
    here = os.path.dirname(path)

    # 1. markdown links to .md
    for link in LINK_RE.findall(text):
        link = link.strip()
        if link.startswith(("http://", "https://", "mailto:", "#")):
            continue
        target = link.split("#", 1)[0]
        if not target.endswith(".md"):
            continue
        resolved = resolve(here, target)
        if not os.path.isfile(resolved):
            errors.append(f"{path}: markdown link -> {link} (resolved {resolved}) does not exist")

    # 2. bare backtick filenames must be host-resolvable from this file.
    #    Skip link labels: [`name.md`](href)
    for m in BACKTICK_MD_RE.finditer(text):
        tok = m.group(1)
        if text[m.end():m.end() + 2] == "](":
            continue
        base = os.path.basename(tok)
        if base in WORKSPACE_ARTIFACTS or base in PROJECT_DOCS:
            continue
        if any(tok.startswith(p) for p in ALLOW_PATH_PREFIXES):
            continue

        if "/" in tok:
            resolved = resolve(here, tok)
            if os.path.isfile(resolved):
                continue
            # Intentional skills-root-relative tokens (adapter tables, inventories).
            alt = os.path.normpath(os.path.join(SKILLS_ROOT, tok))
            if os.path.isfile(alt):
                continue
            errors.append(f"{path}: backtick `{tok}` does not resolve")
            continue

        if any(os.path.isfile(c) for c in naive_local_candidates(path, base)):
            continue
        if base in all_basenames:
            errors.append(
                f"{path}: bare `{tok}` is not local to this skill path; use a "
                f"relative markdown link to the shared file (hosts open "
                f"<skill>/reference/{tok} for bare names)"
            )
            continue
        errors.append(f"{path}: backtick `{tok}`: no `{base}` exists anywhere in the pack")

    # 4. "(see X.md)" prose pointers: slash form resolves (install-aware);
    #    bare form must be local-resolvable or a workspace/project doc.
    for tok in SEE_RE.findall(text):
        base = os.path.basename(tok)
        if base in WORKSPACE_ARTIFACTS or base in PROJECT_DOCS:
            continue
        if any(tok.startswith(p) for p in ALLOW_PATH_PREFIXES):
            continue
        if "/" in tok:
            resolved = resolve(here, tok)
            if not os.path.isfile(resolved):
                errors.append(f"{path}: (see {tok}) (resolved {resolved}) does not exist")
        elif not any(os.path.isfile(c) for c in naive_local_candidates(path, base)):
            if base in all_basenames:
                errors.append(
                    f"{path}: (see {tok}): bare name is not local; use a relative path"
                )
            else:
                errors.append(f"{path}: (see {tok}): no `{base}` exists anywhere in the pack")

    # 3. "canonical version: `path`" must resolve against the skills root
    for claim in CANONICAL_RE.findall(text):
        resolved = os.path.normpath(os.path.join(SKILLS_ROOT, claim))
        if not os.path.isfile(resolved):
            errors.append(f"{path}: 'canonical version' -> {claim} (resolved {resolved}) does not exist")

    # 4. Unquoted skill/reference paths are join-hazards: hosts attach the token
    #    to the current skill instead of the named skill tree.
    comment_spans = [(m.start(), m.end()) for m in HTML_COMMENT_RE.finditer(text)]
    link_spans = [(m.start(), m.end()) for m in LINK_RE.finditer(text)]
    for m in UNQUOTED_SKILL_PATH_RE.finditer(text):
        start, end = m.start(), m.end()
        if any(a <= start < b for a, b in comment_spans):
            continue
        if any(a <= start < b for a, b in link_spans):
            continue
        if start >= 2 and text[start - 2:start] == "](":
            continue
        if start > 0 and text[start - 1] in "`/<":
            continue
        if end < len(text) and text[end] == "`":
            continue
        if any(text[:start].endswith(prefix) for prefix in HOST_SKILL_PREFIXES):
            continue
        tok = m.group(0)
        local = os.path.normpath(os.path.join(here, tok))
        if os.path.isfile(local):
            continue
        skills = os.path.normpath(os.path.join(SKILLS_ROOT, tok))
        if os.path.isfile(skills):
            errors.append(
                f"{path}: unquoted `{tok}` is a join-hazard; hosts attach it to "
                f"the current skill. Use `.claude/skills/{tok}` or a relative "
                f"markdown link"
            )
        else:
            errors.append(
                f"{path}: unquoted `{tok}` does not exist at the skills root"
            )

if errors:
    print(f"check-cross-refs: {len(errors)} dead reference(s):\n")
    for e in sorted(errors):
        print("  " + e)
    sys.exit(1)

print(f"check-cross-refs: OK: {len(md_files)} markdown files, no dead references.")
